version: "3.1"
services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/internal_download:latest
    command: bash
    volumes:
      - $PWD:/workdir
  app_service:
    image: islasgeci/internal_download:latest
    container_name: "core-api-container"
    entrypoint: ["streamlit", "run", "src/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"
    volumes:
      - $PWD/tabular_data_packages:/workdir/data
  external_ui_develop:
    image: islasgeci/internal_download:latest
    container_name: "external_ui_develop"
    entrypoint: ["streamlit", "run", "src/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8502:8501"
    volumes:
      - $PWD/geci-internal-download:/workdir
      - $PWD/tabular_data_packages:/workdir/data
    networks:
      - geci
  data_api:
    image: islasgeci/geci_data:latest
    entrypoint: ["uvicorn", "geci_data.api:app", "--host", "0.0.0.0", "--port", "10000"]
    volumes:
      - $PWD/geci-data:/workdir
      - $PWD/tabular_data_packages:/workdir/data
    networks:
      - geci

networks:
  geci:
